version: '3.8'
services:
    db:
        image: "postgres"
        container_name: db
        env_file:
            - .env.postgres
        volumes:
            - db-data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    api:
        container_name: api
        restart: always
        build:
          context: ./api/
          dockerfile: ../dockerfile/Dockerfile.api
        depends_on:
            - db
        volumes:
            - ./api:/var/www/app/

    app:
        container_name: app
        build:
          context: ./app/
          dockerfile: ../dockerfile/Dockerfile.react
        volumes:
            - ./app/src:/app/src
            - ./app/public:/app/public
            - ./app/assets:/app/assets
        ports:
            - "3000:3000"
        stdin_open: true
        environment:
          - CHOKIDAR_USEPOLLING=true
volumes:
    db-data:
