version: "3.7"
services:
  # DATABASE
  postgres:
    image: postgres:13.1
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:3210:5432"
    env_file: ./env/.env.postgres

  # BACKEND
  api-gateway:
    build:
      dockerfile: ./dockerfile.develop
      context: ./api/api-gateway
    env_file:
      - ./env/.env.global
      - ./env/.env.gateway
    ports:
      - "127.0.0.1:3200:7000"
    volumes:
      - ./api-gateway/src:/home/node/app/src

  song-service:
    build:
      dockerfile: ./dockerfile.develop
      context: ./api/song-service
    volumes:
      - ./song-service/src:/home/node/app/src
    env_file:
      - ./env/.env.global
      - ./env/.env.song-service

    # FRONTEND
    app:
      container_name: app
      build:
        context: ./app/
        dockerfile: ../dockerfile/Dockerfile.react
      volumes:
        - ./app/src:/app/src
        - ./app/public:/app/public
        - ./app/assets:/app/assets
      ports:
        - "3000:3000"
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
volumes:
  database:
    name: database
